[WIP] Add PixuraSearchBar component
Pixura/pixura-react-sdk pull request #2
Opened 2018-10-09 09:21 UTC by bakaoh

Fix: #1

2018-10-10 16:07 UTC, charlescrain commented
@bakaoh Hey! It's looking great! I cloned and realized I put the wrong API in the description. I updated it, `https://ropsten-api.pixura.io/elasticsearch` is the url i meant to provide you. 

I got it working locally and was able to search and see the results logged in the console. Super stoked!!

Some react errors after running the query but can see the results logged so looks pretty close to done 😄

2018-10-10 16:08 UTC, charlescrain requested changes

2018-10-10 16:08 UTC, charlescrain commented on src/App.js
> +                  elasticSearchUrl="https://ropsten-graph.pixura.io/elasticsearch"
if you could change this line to use `https://ropsten-api.pixura.io/elasticsearch` it should be working!

2018-10-11 07:04 UTC, bakaoh commented
@charlescrain --- i updated the api url and fixed the bug ^^

2018-10-15 16:21 UTC, charlescrain approved these changes

2018-10-15 16:22 UTC, merged